{
 "title": "Reactor Netty",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Http Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(reactor_netty_http_client_response_time_seconds_count[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Failed Requests Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(reactor_netty_http_client_response_time_seconds_count{status=~\"5..\"}[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(reactor_netty_http_client_response_time_seconds_sum[1m])) / sum(rate(reactor_netty_http_client_response_time_seconds_count[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(reactor_netty_http_client_response_time_seconds_max)",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Connect Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(reactor_netty_http_client_connect_time_seconds_sum[1m])) / sum(rate(reactor_netty_http_client_connect_time_seconds_count[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(reactor_netty_http_client_connect_time_seconds_max)",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Sent & Received Bytes TCP level",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(reactor_netty_http_client_data_received_bytes_sum{uri=~\"http\"}[1m]))",
     "legendFormat": "Received Bytes"
    },
    {
     "expr": "sum(rate(reactor_netty_http_client_data_sent_bytes_sum{uri=~\"http\"}[1m]))",
     "legendFormat": "Sent Bytes"
    }
   ]
  },
  {
   "title": "Sent & Received Bytes Per URI",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(reactor_netty_http_client_data_received_bytes_sum{uri!~\"http\"}[1m]))",
     "legendFormat": "Received Bytes"
    },
    {
     "expr": "sum(rate(reactor_netty_http_client_data_sent_bytes_sum{uri!~\"http\"}[1m]))",
     "legendFormat": "Sent Bytes"
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(reactor_netty_connection_provider_http_active_connections)",
     "legendFormat": "active"
    },
    {
     "expr": "sum(reactor_netty_connection_provider_http_idle_connections)",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(reactor_netty_connection_provider_http_pending_connections)",
     "legendFormat": "pending"
    },
    {
     "expr": "sum(reactor_netty_connection_provider_http_total_connections)",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Http Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Requests Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(reactor_netty_http_server_response_time_seconds_count{uri!~\".*actuator.*\"}[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Failed Requests Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(reactor_netty_http_server_response_time_seconds_count{uri!~\".*actuator.*\", status=~\"5..\"}[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(reactor_netty_http_server_response_time_seconds_sum{uri!~\".*actuator.*\"}[1m])) / sum(rate(reactor_netty_http_server_response_time_seconds_count{uri!~\".*actuator.*\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(reactor_netty_http_server_response_time_seconds_max{uri!~\".*actuator.*\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Sent & Received Bytes TCP level",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(reactor_netty_http_server_data_received_bytes_sum{uri=~\"http\"}[1m]))",
     "legendFormat": "Received Bytes"
    },
    {
     "expr": "sum(rate(reactor_netty_http_server_data_sent_bytes_sum{uri=~\"http\"}[1m]))",
     "legendFormat": "Sent Bytes"
    }
   ]
  },
  {
   "title": "Sent & Received Bytes per URI",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(reactor_netty_http_server_data_received_bytes_sum{uri!~\"http|.*actuator.*\"}[1m]))",
     "legendFormat": "Received Bytes"
    },
    {
     "expr": "sum(rate(reactor_netty_http_server_data_sent_bytes_sum{uri!~\"http|.*actuator.*\"}[1m]))",
     "legendFormat": "Sent Bytes"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(reactor_netty_pooled_bytebuf_allocator_used_direct_memory)",
     "legendFormat": "direct"
    },
    {
     "expr": "sum(reactor_netty_pooled_bytebuf_allocator_used_heap_memory)",
     "legendFormat": "heap"
    }
   ]
  }
 ]
}